trigger: none
#  - master

variables:
  nlw_token: $(secret_nlw_token)
  zone_code: pimnV

pool:
  vmImage: 'ubuntu-16.04'

jobs:
- job: RunLoadTest
  displayName: Run NeoLoad Test
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'
  - bash: |
      pip install neoload
      neoload --version
  - bash: |
      cd $(Build.SourcesDirectory)

      neoload --profile openshift --token $(nlw_token) --zone $(zone_code)

      neoload --scenario sanityScenario \
              -f example_test/default.yaml \
              -f example_test/slas/uat.yaml \
              --junitsla $(Common.TestResultsDirectory)/neoload-slas.xml
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: $(Common.TestResultsDirectory)/neoload-slas.xml
      failTaskOnFailedTests: true
