trigger:
  - master

variables:
  nlw_token: $(secret_nlw_token)
  zone_code: pimnV

resources:
  containers:
  - container: dind_python
    image: paulsbruce/dind-python3:1.0.1

pool:
  name: Default
#  vmImage: 'ubuntu-16.04'

jobs:
- job: RunTest
  displayName: Run NeoLoad Test
  container: dind_python
  continueOnError: true
  steps:
  - bash: |
      uname
      ls -latr /
      ls -latr $(Build.SourcesDirectory)
  - bash: |
      cd $(Build.SourcesDirectory)

      pip install neoload

      neoload --version

      neoload --profile openshift --token $(nlw_token) --zone $(zone_code)

      neoload --scenario sanityScenario \
              -f example_test/default.yaml \
              -f example_test/slas/uat.yaml \
              --junitsla $(Common.TestResultsDirectory)/neoload-slas.xml
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: $(Common.TestResultsDirectory)/neoload-slas.xml
      failTaskOnFailedTests: true

- job: AfterTest
  displayName: After Test
  steps:
    - bash: |
        ID=$(docker ps --all --filter since=b89ac00645cb --filter status=running --no-trunc --format "{{.ID}}")
        echo $ID
        docker logs $ID

