trigger:
  - master

variables:
  nlw_token: $(secret_nlw_token)
  zone_code: pimnV

pool:
  vmImage: 'ubuntu-16.04'

jobs:
- job: InstallNeoLoadCLI
  displayName: Install NeoLoad-CLI
  steps:
  - bash: |
      sudo apt-get update && apt-get install py-pip py3-setuptools build-base python2-dev python3-dev
      sudo python3 -m pip install -q --upgrade pip
      pip install neoload
      neoload --version

- job: RunTest
  displayName: Run NeoLoad Test
  continueOnError: true
  steps:
  - bash: |
      cd $(Build.SourcesDirectory)

      neoload --profile openshift --token $(nlw_token) --zone $(zone_code)

      neoload --scenario sanityScenario \
              -f example_test/default.yaml \
              -f example_test/slas/uat.yaml \
              --junitsla $(Common.TestResultsDirectory)/neoload-slas.xml
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: $(Common.TestResultsDirectory)/neoload-slas.xml
      failTaskOnFailedTests: true
