trigger:
  - master

variables:
  nlw_token: $(secret_nlw_token)
  zone_code: pimnV
  wksp: $(Pipeline.Workspace)/s

resources:
  containers:
  - container: dind_python
    image: paulsbruce/dind-python3:1.0
    volumes:
    - /home/vsts/work/1/s:/project

pool:
  demands:
    - agent.os -equals Linux  # run locally
#  vmImage: 'ubuntu-16.04'

container: dind_python

steps:
- bash: |
    uname
    ls -latr /
    ls -latr /project
- bash: |
    pip install neoload

    mkdir results

    neoload --version

    neoload --profile openshift --token $(nlw_token) --zone $(zone_code)

    neoload --scenario sanityScenario \
            -f /project/example_test/default.yaml \
            -f /project/example_test/slas/uat.yaml \
            --junitsla results/neoload-slas.xml

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: $(wksp)/results/neoload-slas.xml
    failTaskOnFailedTests: true
