trigger:
  - master

variables:
  nlw_token: $(secret_nlw_token)
  zone_code: pimnV

resources:
  containers:
  - container: dind_python
    image: paulsbruce/dind-python3:1.0.1

pool:
  name: Default
#  vmImage: 'ubuntu-16.04'

container: dind_python

steps:
- bash: |
    uname
    ls -latr /
    ls -latr $(Build.SourcesDirectory)
- bash: |
    cd $(Build.SourcesDirectory)

    pip install neoload

    neoload --version

    neoload --profile openshift --token $(nlw_token) --zone $(zone_code)

    neoload --scenario sanityScenario \
            -f example_test/default.yaml \
            -f example_test/slas/uat.yaml \
            --junitsla $(Common.TestResultsDirectory)/neoload-slas.xml

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: $(Common.TestResultsDirectory)/neoload-slas.xml
    failTaskOnFailedTests: true
