trigger: none

variables:
  nlw_token: $(secret_nlw_token)
  zone_code: $(nlw_token)
  wksp: $(Pipeline.Workspace)/s

pool:
  vmImage: 'ubuntu-16.04'

steps:
- bash: |
    docker --version
    docker ps -a

- bash: |
    sudo apt-get install python3-pip
    python3 -m pip install -q --upgrade pip

- bash: |
    sudo apt-get install python3-pip
    python3 --version
